"""GitHubLabor — Engineering Pipeline GitHub operations labor.

Implements M5_GITMERGE:
- Create feature branch
- Commit changes
- Create PR
- Merge to main (if auto-merge enabled)
"""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path
from typing import Any

from hermes_os.labor_registry import LaborResult

logger = logging.getLogger(__name__)


class GitHubLabor:
    """Labor unit for GitHub operations."""

    def __init__(self, remote: str = "origin", **kwargs) -> None:
        self.remote = remote

    async def execute(self, workspace: Path, task_description: str, meta: dict[str, Any]) -> LaborResult:
        """
        Execute GitHub operations.

        M5_GITMERGE tasks:
        - Create feature branch
        - Commit changes
        - Create PR
        - Optionally merge
        """
        stage = meta.get("stage", "M5_GITMERGE")

        if stage == "M5_GITMERGE":
            return await self._execute_git_merge(workspace, task_description, meta)
        else:
            return await self._execute_generic(workspace, task_description, meta)

    async def _execute_git_merge(
        self, workspace: Path, task_description: str, meta: dict[str, Any]
    ) -> LaborResult:
        """M5_GITMERGE: Create PR and merge to main."""
        branch_name = meta.get("branch_name", "feature/generated")
        commit_message = meta.get("commit_message", "feat: add generated code")
        auto_merge = meta.get("auto_merge", False)

        logger.info("GitHubLabor M5_GITMERGE: branch=%s, auto_merge=%s", branch_name, auto_merge)

        try:
            # 1. Configure git user (if not set)
            await self._run_git(workspace, ["config", "user.email", "hermes-os@ai.system"])
            await self._run_git(workspace, ["config", "user.name", "Hermes OS"])

            # 2. Create and checkout branch
            await self._run_git(workspace, ["checkout", "-b", branch_name])

            # 3. Stage all changes
            await self._run_git(workspace, ["add", "-A"])

            # 4. Commit
            result = await self._run_git(workspace, ["commit", "-m", commit_message])

            # 5. Push to remote
            await self._run_git(workspace, ["push", "-u", self.remote, branch_name])

            # 6. Create PR (using gh CLI if available)
            pr_result = await self._create_pr(workspace, branch_name, commit_message)

            if not pr_result:
                logger.warning("PR creation failed or gh CLI not available")
                # Still return True if commit/push succeeded
                return LaborResult(
                    success=True,
                    output=f"M5_GITMERGE: branch {branch_name} created and pushed, PR creation skipped",
                    token_usage=0,
                )

            # 7. Auto-merge if enabled
            if auto_merge:
                await self._merge_pr(workspace, branch_name)

            # Write output
            output_file = workspace / "src" / "git_output.txt"
            output_file.write_text(
                f"Branch: {branch_name}\nPR: created\nAuto-merge: {auto_merge}", encoding="utf-8"
            )

            return LaborResult(
                success=True,
                output=f"M5_GITMERGE: branch {branch_name} created, PR created, auto_merge={auto_merge}",
                token_usage=0,
            )

        except Exception as e:
            logger.exception("M5_GITMERGE exception")
            return LaborResult(
                success=False,
                output="",
                token_usage=0,
                error=str(e),
            )

    async def _run_git(self, workspace: Path, args: list[str]) -> subprocess.CompletedProcess:
        """Run a git command."""
        cmd = ["git"] + args
        proc = await subprocess.create_subprocess_exec(
            *cmd,
            cwd=str(workspace),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        result = subprocess.CompletedProcess(
            args=cmd,
            returncode=proc.returncode or 0,
            stdout=stdout.decode("utf-8", errors="replace"),
            stderr=stderr.decode("utf-8", errors="replace"),
        )
        if result.returncode != 0:
            logger.warning("Git command failed: %s %s", " ".join(args), result.stderr)
        return result

    async def _create_pr(self, workspace: Path, branch_name: str, title: str) -> bool:
        """Create a PR using gh CLI."""
        try:
            cmd = [
                "gh",
                "pr",
                "create",
                "--title",
                title,
                "--body",
                "Generated by Hermes OS Engineering Pipeline",
                "--base",
                "main",
                "--head",
                branch_name,
            ]
            proc = await subprocess.create_subprocess_exec(
                *cmd,
                cwd=str(workspace),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            _, _ = await proc.communicate()
            return proc.returncode == 0
        except FileNotFoundError:
            logger.warning("gh CLI not installed")
            return False
        except Exception as e:
            logger.warning("PR creation failed: %s", e)
            return False

    async def _merge_pr(self, workspace: Path, branch_name: str) -> bool:
        """Merge the PR after checks pass."""
        try:
            cmd = ["gh", "pr", "merge", "--admin", "--squash", branch_name]
            proc = await subprocess.create_subprocess_exec(
                *cmd,
                cwd=str(workspace),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            _, _ = await proc.communicate()
            return proc.returncode == 0
        except Exception as e:
            logger.warning("PR merge failed: %s", e)
            return False

    async def _execute_generic(
        self, workspace: Path, task_description: str, meta: dict[str, Any]
    ) -> LaborResult:
        """Generic git operation fallback."""
        logger.info("GitHubLabor generic operation")
        return LaborResult(
            success=True,
            output=f"GitHubLabor generic operation completed for: {task_description[:50]}",
            token_usage=0,
        )