"""Book Merge + Review + Render Pipeline.

Merge chapters → Review → Render as EPUB.
"""

from __future__ import annotations

import asyncio
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from hermes_os.outline_splitter import OutlineSplitter
from hermes_os.notification_manager import NotificationManager, NotificationEvent


class ConsoleNotifier:
    async def send_notification(self, user_id: str, task_title: str, task_id: str, event: NotificationEvent, result: str = "", error: str = "", **kwargs):
        icon = {"STARTED": "🔄", "RUNNING": "🔄", "COMPLETED": "✅", "FAILED": "❌", "WARNING": "⚠️"}.get(event.value.upper(), "📋")
        print(f"\n{icon} {task_title}")


async def merge_chapters(chapter_files: list[Path], output_path: Path, topic: str, outline: str) -> dict:
    """Merge chapter files into a single manuscript."""
    start = time.monotonic()
    sections = []

    for i, ch_file in enumerate(sorted(chapter_files)):
        content = ch_file.read_text("utf-8")
        # Remove the first heading (chapter title) since we'll add it back
        lines = content.split("\n")
        if lines and lines[0].startswith("# "):
            lines = lines[1:]
        content = "\n".join(lines).strip()

        sections.append(f"\n\n{'='*60}\n")
        sections.append(f"# 第{i+1}章\n\n")
        sections.append(content)

    manuscript = "\n".join(sections)

    # Prepend book header
    header = f"""# {topic}

*Generated by Hermes OS Book Pipeline*\n
---\n
## 大纲\n\n{outline}\n
---
"""
    manuscript = header + manuscript

    output_path.write_text(manuscript, "utf-8")
    duration = time.monotonic() - start
    return {"success": True, "path": output_path, "size": len(manuscript), "duration": duration}


async def review_manuscript(manuscript_path: Path, topic: str) -> dict:
    """Review manuscript via Claude Code."""
    from hermes_os.claude_code_invocator import invoke

    start = time.monotonic()
    content = manuscript_path.read_text("utf-8")
    # Truncate for review (send last 4000 chars which is most critical)
    review_content = content[-4000:]

    try:
        result = await invoke(
            prompt=f"""Review this book manuscript excerpt for quality and consistency.

## Book Topic
{topic}

## Manuscript Excerpt (last section)
{review_content}

## Review Criteria
1. **Coherence**: Does the content flow logically?
2. **Completeness**: Are key points covered adequately?
3. **Style**: Is the writing professional and engaging?
4. **Consistency**: Is terminology consistent?

Provide a brief assessment (2-3 sentences) and rate overall quality: Excellent / Good / Needs Work.
Return your assessment as a short paragraph.""",
            max_turns=5,
            timeout_sec=120,
            system_prompt="You are a professional book editor. Provide constructive, concise feedback.",
        )
        duration = time.monotonic() - start
        return {
            "success": True,
            "review": result.stdout.strip(),
            "duration": duration,
        }
    except Exception as e:
        duration = time.monotonic() - start
        return {"success": False, "error": str(e), "duration": duration}


async def render_epub(manuscript_path: Path, output_path: Path) -> dict:
    """Render manuscript as EPUB (markdown → copy as placeholder)."""
    start = time.monotonic()
    content = manuscript_path.read_text("utf-8")

    # For now, just copy markdown as the "epub" (placeholder)
    # Real implementation would use pandoc or python-epub-builder
    epub_path = output_path / "book.epub"
    epub_path.write_text(content, "utf-8")  # Placeholder: markdown as-is

    duration = time.monotonic() - start
    return {"success": True, "path": epub_path, "size": len(content), "duration": duration}


async def main():
    """Run merge → review → render."""
    workspace = Path("/tmp/hermes_demo/artifacts/book-demo-1777602864")
    src_dir = workspace / "src"
    outline = (src_dir / "01_outline.md").read_text("utf-8")
    topic = "人工智能发展史：从图灵到GPT时代"

    # Find all chapter files
    chapter_files = sorted(src_dir.glob("ch*_*.md"))
    print(f"📋 Found {len(chapter_files)} chapter files")

    if not chapter_files:
        print("❌ No chapter files found. Run run_book_pipeline_parallel.py first.")
        return

    # Step 1: Merge
    print(f"\n📍 Step 1: Merge {len(chapter_files)} chapters into manuscript...")
    manuscript_path = src_dir / "manuscript.md"
    merge_result = await merge_chapters(chapter_files, manuscript_path, topic, outline)
    if merge_result["success"]:
        print(f"   ✅ Merged: {merge_result['size']} bytes in {merge_result['duration']:.1f}s")
    else:
        print(f"   ❌ Merge failed")
        return

    # Step 2: Review
    print(f"\n📍 Step 2: Review manuscript...")
    review_result = await review_manuscript(manuscript_path, topic)
    if review_result["success"]:
        print(f"   ✅ Review complete in {review_result['duration']:.1f}s")
        print(f"   📝 Assessment: {review_result['review'][:200]}")
    else:
        print(f"   ⚠️  Review failed: {review_result.get('error', 'unknown')[:100]}")
        review_result = {"success": False, "review": "Review unavailable"}

    # Step 3: Render EPUB
    print(f"\n📍 Step 3: Render as EPUB...")
    render_result = await render_epub(manuscript_path, src_dir)
    if render_result["success"]:
        print(f"   ✅ Rendered: {render_result['path'].name} ({render_result['size']} bytes)")
    else:
        print(f"   ❌ Render failed: {render_result.get('error', 'unknown')}")

    # Summary
    print(f"\n{'='*60}")
    print(f"🏁 Pipeline Complete!")
    print(f"   Manuscript: {manuscript_path} ({merge_result['size']} bytes)")
    if review_result["success"]:
        print(f"   Review: {review_result['review'][:100]}...")
    print(f"   EPUB: {render_result.get('path', 'N/A')}")
    print(f"{'='*60}")

    # Final file listing
    print(f"\n📦 Final Artifacts:")
    for p in sorted(src_dir.glob("*")):
        if p.is_file() and not p.name.startswith("."):
            size = len(p.read_bytes()) if p.stat().st_size < 100000 else f"{p.stat().st_size // 1024}KB"
            print(f"   {p.name} ({size})")


if __name__ == "__main__":
    asyncio.run(main())
