"""GeneEngine — Oct-OS inspired evolution engine for Hermes OS.

Implements three evolutionary patterns from Oct-OS:
1. Antibody Genes — immune memory for failure patterns
2. Gene Pool — tracking successful prompt strategies
3. Differentiation — auto-spawning specialized agents for recurring failures

Usage:
    engine = GeneEngine()
    await engine.record_failure(error_pattern, fix_strategy)
    await engine.get_antibody(error_pattern)  # Returns fix if exists
    await engine.record_success(prompt, context, outcome)
    specialized = await engine.check_differentiation(failure_count)
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger("hermes_os.gene_engine")


# ---------------------------------------------------------------------------
# Gene Data Structures
# ---------------------------------------------------------------------------


@dataclass
class AntibodyGene:
    """An antibody gene — a fix strategy for a known failure pattern."""

    pattern: str  # Regex or key pattern that identifies this failure
    fix_strategy: str  # Prompt or approach that fixes this
    failure_count: int = 0  # How many times this pattern was encountered
    success_count: int = 0  # How many times the fix worked
    last_seen: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    created_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    @property
    def effectiveness(self) -> float:
        """Effectiveness score = success / failure ratio."""
        return self.success_count / max(1, self.failure_count)

    def to_dict(self) -> dict[str, Any]:
        return {
            "pattern": self.pattern,
            "fix_strategy": self.fix_strategy,
            "failure_count": self.failure_count,
            "success_count": self.success_count,
            "last_seen": self.last_seen,
            "created_at": self.created_at,
            "effectiveness": self.effectiveness,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> AntibodyGene:
        return cls(
            pattern=data["pattern"],
            fix_strategy=data["fix_strategy"],
            failure_count=data.get("failure_count", 0),
            success_count=data.get("success_count", 0),
            last_seen=data.get("last_seen", datetime.now(UTC).isoformat()),
            created_at=data.get("created_at", datetime.now(UTC).isoformat()),
        )


@dataclass
class SuccessfulGene:
    """A successful prompt strategy that can be reused."""

    prompt_template: str
    context_type: str  # e.g., "code_generation", "research", "review"
    outcome: str  # "success" | "partial" | "failed"
    use_count: int = 0
    success_rate: float = 0.0
    last_used: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    created_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_dict(self) -> dict[str, Any]:
        return {
            "prompt_template": self.prompt_template,
            "context_type": self.context_type,
            "outcome": self.outcome,
            "use_count": self.use_count,
            "success_rate": self.success_rate,
            "last_used": self.last_used,
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> SuccessfulGene:
        return cls(
            prompt_template=data["prompt_template"],
            context_type=data.get("context_type", ""),
            outcome=data.get("outcome", "success"),
            use_count=data.get("use_count", 0),
            success_rate=data.get("success_rate", 0.0),
            last_used=data.get("last_used", datetime.now(UTC).isoformat()),
            created_at=data.get("created_at", datetime.now(UTC).isoformat()),
        )


# ---------------------------------------------------------------------------
# Specialized Agent Template (for Differentiation)
# ---------------------------------------------------------------------------

SPECIALIZED_AGENT_TEMPLATE = '''"""Specialized {agent_type} Agent — auto-generated by GeneEngine Differentiation.

This agent was auto-generated because the generic pipeline repeatedly failed
on {failure_pattern} tasks.

Pattern: {failure_pattern}
Fix: {fix_strategy}
Created: {created_at}
"""

from __future__ import annotations

import re
from typing import Any


class Specialized{agent_type}Agent:
    """Specialized agent for {agent_type} tasks with embedded immunity to {failure_pattern}."""

    def __init__(self) -> None:
        self._failure_pattern = "{failure_pattern}"
        self._fix_strategy = """{fix_strategy}"""

    def can_handle(self, task_description: str) -> bool:
        """Check if this specialized agent can handle the task."""
        indicators = {indicators_list}
        return any(indicator in task_description.lower() for indicator in indicators)

    def get_optimized_prompt(self, base_prompt: str) -> str:
        """Return an optimized prompt with pattern-specific fixes embedded."""
        return f"""
## Specialized Mode: {agent_type}

Task: {{base_prompt}}

## Pattern-Specific Guidance (learned from previous failures):
{{self._fix_strategy}}

## Additional Constraints:
- Be extra careful about: {{self._failure_pattern}}
""".format(base_prompt=base_prompt, **{{"self": self}})

    async def execute(self, task: str, context: dict[str, Any]) -> dict[str, Any]:
        """Execute the task with specialized handling."""
        from hermes_os.claude_code_invocator import invoke

        prompt = self.get_optimized_prompt(task)
        result = await invoke(
            prompt=prompt,
            system_prompt="You are a specialized {agent_type} agent with deep expertise in {failure_pattern} patterns.",
            max_turns=context.get("max_turns", 20),
            timeout_sec=context.get("timeout_sec", 300),
        )
        return {{"success": True, "output": result.stdout, "agent": "{agent_type}"}}
'''


# ---------------------------------------------------------------------------
# GeneEngine
# ---------------------------------------------------------------------------


class GeneEngine:
    """
    Evolution engine for Hermes OS — tracks failures, successes, and auto-generates specialized agents.

    Storage structure:
      ~/.hermes/genes/
        antibody_genes.json    — failure patterns → fix strategies
        gene_pool.json         — successful prompt strategies
        specialized_agents/     — auto-generated specialized agent files
    """

    DIFFERENTIATION_THRESHOLD = 3  # failures before spawning specialized agent

    def __init__(self, base_dir: Path | str | None = None) -> None:
        self._base_dir = Path(base_dir or Path.home() / ".hermes" / "genes")
        self._base_dir.mkdir(parents=True, exist_ok=True)
        self._antibody_path = self._base_dir / "antibody_genes.json"
        self._gene_pool_path = self._base_dir / "gene_pool.json"
        self._specialized_dir = self._base_dir / "specialized_agents"
        self._specialized_dir.mkdir(exist_ok=True)
        self._logger = logging.getLogger("hermes_os.gene_engine")

    # -------------------------------------------------------------------------
    # Antibody Genes — Immune Memory
    # -------------------------------------------------------------------------

    def _load_antibody_genes(self) -> dict[str, AntibodyGene]:
        """Load antibody genes from disk."""
        if not self._antibody_path.exists():
            return {}
        try:
            data = json.loads(self._antibody_path.read_text("utf-8"))
            return {k: AntibodyGene.from_dict(v) for k, v in data.items()}
        except (json.JSONDecodeError, KeyError):
            return {}

    def _save_antibody_genes(self, genes: dict[str, AntibodyGene]) -> None:
        """Save antibody genes to disk."""
        data = {k: v.to_dict() for k, v in genes.items()}
        self._antibody_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), "utf-8")

    def record_failure(
        self,
        error_pattern: str,
        error_context: str,
        fix_strategy: str | None = None,
    ) -> AntibodyGene:
        """Record a failure and optionally a fix strategy.

        If the pattern already exists, increment its failure_count.
        If fix_strategy is provided, update the gene's fix.
        """
        genes = self._load_antibody_genes()

        if error_pattern in genes:
            gene = genes[error_pattern]
            gene.failure_count += 1
            gene.last_seen = datetime.now(UTC).isoformat()
            if fix_strategy and fix_strategy != gene.fix_strategy:
                gene.fix_strategy = fix_strategy
        else:
            gene = AntibodyGene(
                pattern=error_pattern,
                fix_strategy=fix_strategy or "",
                failure_count=1,
                success_count=0,
            )
            genes[error_pattern] = gene

        self._save_antibody_genes(genes)
        self._logger.info(
            "Recorded antibody gene: pattern=%s failure_count=%d", error_pattern, gene.failure_count
        )

        # Check if differentiation is needed
        if gene.failure_count >= self.DIFFERENTIATION_THRESHOLD and gene.fix_strategy:
            self._maybe_differentiate(error_pattern, gene)

        return gene

    def record_success_for_pattern(self, error_pattern: str) -> None:
        """Record that a fix worked for this pattern."""
        genes = self._load_antibody_genes()
        if error_pattern in genes:
            gene = genes[error_pattern]
            gene.success_count += 1
            gene.last_seen = datetime.now(UTC).isoformat()
            self._save_antibody_genes(genes)
            self._logger.info(
                "Antibody %s worked! success_count=%d", error_pattern, gene.success_count
            )

    def get_antibody(self, error_pattern: str) -> AntibodyGene | None:
        """Get an antibody gene for a pattern if one exists."""
        genes = self._load_antibody_genes()
        return genes.get(error_pattern)

    def get_all_antibody_genes(self) -> list[AntibodyGene]:
        """Get all antibody genes ordered by effectiveness."""
        genes = self._load_antibody_genes()
        return sorted(genes.values(), key=lambda g: -g.effectiveness)

    # -------------------------------------------------------------------------
    # Gene Pool — Successful Strategies
    # -------------------------------------------------------------------------

    def _load_gene_pool(self) -> dict[str, SuccessfulGene]:
        """Load gene pool from disk."""
        if not self._gene_pool_path.exists():
            return {}
        try:
            data = json.loads(self._gene_pool_path.read_text("utf-8"))
            return {k: SuccessfulGene.from_dict(v) for k, v in data.items()}
        except (json.JSONDecodeError, KeyError):
            return {}

    def _save_gene_pool(self, genes: dict[str, SuccessfulGene]) -> None:
        """Save gene pool to disk."""
        data = {k: v.to_dict() for k, v in genes.items()}
        self._gene_pool_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), "utf-8")

    def record_success(
        self,
        prompt: str,
        context_type: str,
        outcome: str = "success",
    ) -> SuccessfulGene:
        """Record a successful prompt strategy."""
        pool = self._load_gene_pool()

        # Create key from prompt hash (first 64 chars)
        key = prompt[:64] if len(prompt) >= 64 else prompt

        if key in pool:
            gene = pool[key]
            gene.use_count += 1
            gene.last_used = datetime.now(UTC).isoformat()
            # Update success rate
            if outcome == "success":
                gene.success_rate = (
                    gene.success_rate * (gene.use_count - 1) + 1.0
                ) / gene.use_count
            elif outcome == "failed":
                gene.success_rate = gene.success_rate * (gene.use_count - 1) / gene.use_count
        else:
            gene = SuccessfulGene(
                prompt_template=prompt[:500],  # Store first 500 chars
                context_type=context_type,
                outcome=outcome,
                use_count=1,
                success_rate=1.0 if outcome == "success" else 0.0,
            )
            pool[key] = gene

        self._save_gene_pool(pool)
        self._logger.info(
            "Recorded gene in pool: context=%s use_count=%d", context_type, gene.use_count
        )
        return gene

    def get_best_strategy(self, context_type: str) -> SuccessfulGene | None:
        """Get the most successful strategy for a context type."""
        pool = self._load_gene_pool()
        candidates = [g for g in pool.values() if g.context_type == context_type]
        if not candidates:
            return None
        return max(candidates, key=lambda g: g.success_rate * min(g.use_count, 10))

    # -------------------------------------------------------------------------
    # Differentiation — Auto-spawn Specialized Agents
    # -------------------------------------------------------------------------

    def _maybe_differentiate(self, error_pattern: str, gene: AntibodyGene) -> bool:
        """Check if we should spawn a specialized agent for this pattern.

        Returns True if a specialized agent was created.
        """
        if gene.fix_strategy:
            self._logger.info(
                "Threshold reached for pattern %s, spawning specialized agent", error_pattern
            )
            return self._spawn_specialized_agent(error_pattern, gene)
        return False

    def _spawn_specialized_agent(self, error_pattern: str, gene: AntibodyGene) -> bool:
        """Spawn a specialized agent file for this error pattern."""
        try:
            # Determine agent type from pattern
            agent_type = self._infer_agent_type(error_pattern)

            # Generate specialized agent file
            agent_code = self._generate_agent_code(error_pattern, gene, agent_type)

            # Write to specialized_agents directory
            safe_name = re.sub(r"[^a-zA-Z0-9]", "_", error_pattern)[:30]
            agent_path = self._specialized_dir / f"{safe_name}_agent.py"

            agent_path.write_text(agent_code, "utf-8")
            self._logger.info("Spawned specialized agent: %s", agent_path)

            return True
        except Exception as e:
            self._logger.error(
                "Failed to spawn specialized agent for %s: %s", error_pattern, str(e)
            )
            return False

    def _infer_agent_type(self, error_pattern: str) -> str:
        """Infer the agent type from the error pattern."""
        pattern_lower = error_pattern.lower()

        if any(k in pattern_lower for k in ["syntax", "indentation", "import"]):
            return "CodeFix"
        elif any(k in pattern_lower for k in ["test", "assert", "pytest"]):
            return "TestFix"
        elif any(k in pattern_lower for k in ["format", "lint", "style"]):
            return "FormatFix"
        elif any(k in pattern_lower for k in ["api", "http", "request"]):
            return "API"
        elif any(k in pattern_lower for k in ["db", "sql", "query"]):
            return "Database"
        elif any(k in pattern_lower for k in ["security", "injection", "xss"]):
            return "Security"
        else:
            return "General"

    def _generate_agent_code(self, error_pattern: str, gene: AntibodyGene, agent_type: str) -> str:
        """Generate the specialized agent Python code."""
        indicators = self._extract_indicators(error_pattern)

        template = SPECIALIZED_AGENT_TEMPLATE.format(
            agent_type=agent_type,
            failure_pattern=error_pattern.replace('"', '\\"'),
            fix_strategy=gene.fix_strategy.replace('"', '\\"').replace("\n", "\n        "),
            created_at=datetime.now(UTC).isoformat(),
            indicators_list=str(indicators),
        )
        return template

    def _extract_indicators(self, error_pattern: str) -> list[str]:
        """Extract key indicators from error pattern for can_handle matching."""
        # Extract significant words (length > 3)
        words = [w for w in error_pattern.split() if len(w) > 3]
        return words[:5]  # Return top 5 indicators

    def list_specialized_agents(self) -> list[dict[str, str]]:
        """List all available specialized agents."""
        agents = []
        for path in self._specialized_dir.glob("*_agent.py"):
            agents.append(
                {
                    "name": path.stem,
                    "path": str(path),
                    "size": path.stat().st_size,
                }
            )
        return agents

    # -------------------------------------------------------------------------
    # Gene Decay — Remove stale genes
    # -------------------------------------------------------------------------

    def apply_gene_decay(self, days_threshold: int = 30) -> int:
        """Remove antibody genes that haven't been used in days_threshold days.

        Returns the number of genes removed.
        """
        genes = self._load_antibody_genes()
        from datetime import timedelta

        cutoff_date = datetime.now(UTC) - timedelta(days=days_threshold)

        to_remove = []
        for pattern, gene in genes.items():
            last_seen = datetime.fromisoformat(gene.last_seen)
            if last_seen < cutoff_date and gene.success_count > 2:
                to_remove.append(pattern)

        for pattern in to_remove:
            del genes[pattern]

        if to_remove:
            self._save_antibody_genes(genes)
            self._logger.info("Gene decay removed %d stale genes", len(to_remove))

        return len(to_remove)
